import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  //const [conversationId, setConversationId] = useState<string|undefined>();
  //const t = api.gpt.getGptResponse.useQuery({
  //  userContent: "Are they secure against quantum computers?",
  //  conversationId: "chatcmpl-6pVXPLm7zobca4TqT6ykxg56MFYpD"
  //});

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        Hello world
      </main>
    </>
  );
};

export default Home;
